name: FedCAP
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.2
  - python=3.8.16
  - readline=8.2
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - antlr4-python3-runtime==4.9.3
      - cachetools==5.5.0
      - calmsize==0.1.3
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - clarabel==0.9.0
      - click==8.1.7
      - contourpy==1.1.1
      - cssselect==1.2.0
      - cssutils==2.11.1
      - cvxpy==1.5.2
      - cycler==0.12.1
      - cython==3.0.11
      - directory-tree==1.0.0
      - docker-pycreds==0.4.0
      - ecos==2.0.14
      - fonttools==4.53.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h5py==3.11.0
      - hdmedians==0.14.2
      - idna==3.8
      - importlib-resources==6.4.4
      - joblib==1.4.2
      - jstyleson==0.0.2
      - kiwisolver==1.4.5
      - lxml==5.3.0
      - matplotlib==3.7.5
      - more-itertools==10.4.0
      - numpy==1.24.4
      - omegaconf==2.3.0
      - opacus==1.1.0
      - osqp==0.6.7.post1
      - packaging==24.1
      - pandas==2.0.3
      - pillow==10.4.0
      - platformdirs==4.2.2
      - premailer==3.10.0
      - protobuf==5.27.3
      - psutil==6.0.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - qdldl==0.1.7.post4
      - requests==2.32.3
      - rptree==0.1.1
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - scs==3.2.7
      - seaborn==0.13.2
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - threadpoolctl==3.5.0
      - torchaudio==0.8.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - ujson==5.10.0
      - urllib3==2.2.2
      - vpdb==1.0.0
      - wandb==0.17.7
      - yagmail==0.15.293
      - zipp==3.20.0
